services:
  postgres-test:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB: waffarhacars_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d waffarhacars_test"]
      interval: 3s
      timeout: 3s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data
